import jsPDF from "jspdf";
import type { AggregatePayload } from "@/lib/types";

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

export function exportSnapshotJSON(payload: AggregatePayload, locationName: string) {
  downloadBlob(
    JSON.stringify(
      { exported_at: new Date().toISOString(), location: locationName, payload },
      null,
      2,
    ),
    `envirogrid-${slugify(locationName)}.json`,
    "application/json",
  );
}

export function exportSnapshotCSV(payload: AggregatePayload, locationName: string) {
  const rows: string[][] = [
    ["metric", "value", "unit", "source"],
    ["location", locationName, "", ""],
    ["aqi", String(payload.air_quality.aqi ?? ""), "US AQI", payload.air_quality.source],
    ["pm25", String(payload.air_quality.pm25 ?? ""), "µg/m³", payload.air_quality.source],
    ["pm10", String(payload.air_quality.pm10 ?? ""), "µg/m³", payload.air_quality.source],
    ["no2", String(payload.air_quality.no2 ?? ""), "ppb", payload.air_quality.source],
    ["o3", String(payload.air_quality.o3 ?? ""), "ppb", payload.air_quality.source],
    ["temperature", String(payload.microclimate.temperature_2m ?? ""), "°C", payload.microclimate.source],
    ["humidity", String(payload.microclimate.relative_humidity_2m ?? ""), "%", payload.microclimate.source],
    ["uv_index", String(payload.microclimate.uv_index ?? ""), "", payload.microclimate.source],
    ["wind_speed", String(payload.microclimate.wind_speed_10m ?? ""), "km/h", payload.microclimate.source],
    ["fire_hotspots", String(payload.fire_hotspots.length), "count", "FIRMS"],
    ["species_observed", String(payload.total_occurrences), "count", "GBIF"],
    ...(payload.history
      ? [
          ["aqi_yesterday", String(payload.history.aqi_yesterday_avg ?? ""), "US AQI", "Open-Meteo"],
          ["temp_avg_30d", String(payload.history.temp_avg_30d ?? ""), "°C", "Open-Meteo archive"],
          ["humidity_avg_30d", String(payload.history.humidity_avg_30d ?? ""), "%", "Open-Meteo archive"],
        ]
      : []),
    ...(payload.aqi_forecast?.map((p) => [
      `forecast_aqi_${p.time}`,
      String(p.us_aqi ?? ""),
      "US AQI",
      "Open-Meteo",
    ]) ?? []),
  ];
  const csv = rows.map((r) => r.map((c) => `"${c.replace(/"/g, '""')}"`).join(",")).join("\r\n");
  downloadBlob(csv, `envirogrid-${slugify(locationName)}.csv`, "text/csv");
}

export function exportSnapshotPDF(payload: AggregatePayload, locationName: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const now = new Date();
  doc.setFillColor(6, 21, 30);
  doc.rect(0, 0, 210, 297, "F");
  doc.setTextColor(16, 185, 129);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("ENVIROGRID SNAPSHOT", 15, 20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(`${locationName}  ·  ${now.toLocaleString()}`, 15, 27);

  const rows: Array<[string, string]> = [
    ["US AQI", `${payload.air_quality.aqi ?? "n/a"} (${payload.air_quality.aqi_category})`],
    ["PM2.5", `${payload.air_quality.pm25 ?? "n/a"} µg/m³`],
    ["PM10", `${payload.air_quality.pm10 ?? "n/a"} µg/m³`],
    ["NO₂", `${payload.air_quality.no2 ?? "n/a"} ppb`],
    ["O₃", `${payload.air_quality.o3 ?? "n/a"} ppb`],
    ["Temperature", `${payload.microclimate.temperature_2m ?? "n/a"} °C`],
    ["Humidity", `${payload.microclimate.relative_humidity_2m ?? "n/a"} %`],
    ["UV index", `${payload.microclimate.uv_index ?? "n/a"}`],
    ["Wind", `${payload.microclimate.wind_speed_10m ?? "n/a"} km/h`],
    ["Active fires (100 km)", `${payload.fire_hotspots.length}`],
    ["Species occurrences", `${payload.total_occurrences}`],
    ...(payload.history
      ? ([
          ["AQI yesterday", `${payload.history.aqi_yesterday_avg ?? "n/a"}`],
          ["30-day mean temp", `${payload.history.temp_avg_30d ?? "n/a"} °C`],
          ["30-day mean humidity", `${payload.history.humidity_avg_30d ?? "n/a"} %`],
        ] as [string, string][])
      : []),
  ];

  doc.setFontSize(10);
  let y = 40;
  rows.forEach(([k, v], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(15, 40, 48);
      doc.rect(15, y - 4, 180, 8, "F");
    }
    doc.setTextColor(203, 213, 225);
    doc.setFont("helvetica", "bold");
    doc.text(k, 20, y + 1);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(52, 211, 153);
    doc.text(v, 120, y + 1);
    y += 10;
  });

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text("Generated by ENVIROGRID 2.0 — data aggregated from Open-Meteo, OpenAQ, NASA FIRMS, GBIF.", 15, 280);
  doc.save(`envirogrid-${slugify(locationName)}.pdf`);
}

function slugify(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "location";
}